import type { FeedbackFlag } from "@/lib/types";

export const feedbackFlags: FeedbackFlag[] = [
  {
    id: "flag-1",
    type: "low_rating",
    status: "open",
    outingId: "outing-9",
    outingTitle: "Classic Film Revival",
    reportedUserId: "user-11",
    reportedUserName: "Chris",
    reporterUserId: "user-6",
    reporterUserName: "Casey",
    summary: "Rated 2/5 — felt conversation was one-sided and member arrived late.",
    rating: 2,
    createdAt: "2026-06-29T10:15:00",
    priority: "high",
  },
  {
    id: "flag-2",
    type: "one_sided_friend",
    status: "open",
    outingId: "outing-9",
    outingTitle: "Classic Film Revival",
    reportedUserId: "user-11",
    reportedUserName: "Chris",
    reporterUserId: "user-1",
    reporterUserName: "Alex",
    summary: "Alex chose 'become friends' but Chris did not reciprocate — flagged for pattern review.",
    createdAt: "2026-06-30T08:42:00",
    priority: "medium",
  },
  {
    id: "flag-3",
    type: "no_show",
    status: "reviewing",
    outingId: "outing-9",
    outingTitle: "Classic Film Revival",
    reportedUserId: "user-12",
    reportedUserName: "Pat",
    reporterUserId: "user-5",
    reporterUserName: "Morgan",
    summary: "Did not check in or respond in group chat. Ticket unused.",
    createdAt: "2026-06-28T20:05:00",
    priority: "high",
  },
  {
    id: "flag-4",
    type: "low_rating",
    status: "open",
    outingId: "outing-9",
    outingTitle: "Classic Film Revival",
    reportedUserId: "user-13",
    reportedUserName: "Avery",
    reporterUserId: "user-7",
    reporterUserName: "Taylor",
    summary: "Rated 3/5 — group energy was fine but member dominated discussion.",
    rating: 3,
    createdAt: "2026-06-29T14:30:00",
    priority: "medium",
  },
  {
    id: "flag-5",
    type: "group_conflict",
    status: "resolved",
    outingId: "outing-9",
    outingTitle: "Classic Film Revival",
    reportedUserId: "user-14",
    reportedUserName: "Blake",
    reporterUserId: "user-2",
    reporterUserName: "Jordan",
    summary: "Minor disagreement about post-film plans — resolved via support follow-up.",
    createdAt: "2026-06-29T09:00:00",
    priority: "low",
  },
  {
    id: "flag-6",
    type: "safety_concern",
    status: "reviewing",
    outingId: "outing-9",
    outingTitle: "Classic Film Revival",
    reportedUserId: "user-15",
    reportedUserName: "Reese",
    reporterUserId: "user-3",
    reporterUserName: "Sam",
    summary: "Member made others uncomfortable with personal questions — escalated to safety review.",
    createdAt: "2026-06-29T11:20:00",
    priority: "high",
  },
  {
    id: "flag-7",
    type: "one_sided_friend",
    status: "open",
    outingId: "outing-9",
    outingTitle: "Classic Film Revival",
    reportedUserId: "user-16",
    reportedUserName: "Skyler",
    reporterUserId: "user-4",
    reporterUserName: "Riley",
    summary: "Riley requested friendship twice across outings without reciprocation.",
    createdAt: "2026-07-02T16:45:00",
    priority: "medium",
  },
  {
    id: "flag-8",
    type: "low_rating",
    status: "dismissed",
    outingId: "outing-9",
    outingTitle: "Classic Film Revival",
    reportedUserId: "user-17",
    reportedUserName: "Dana",
    reporterUserId: "user-8",
    reporterUserName: "Drew",
    summary: "Rated 3/5 — venue was loud, not a member issue. Dismissed.",
    rating: 3,
    createdAt: "2026-06-29T18:00:00",
    priority: "low",
  },
];

export function getOpenFeedbackFlags(): FeedbackFlag[] {
  return feedbackFlags.filter((f) => f.status === "open" || f.status === "reviewing");
}

export function getFeedbackFlagsByType(type: FeedbackFlag["type"]): FeedbackFlag[] {
  return feedbackFlags.filter((f) => f.type === type);
}
