import type { Outing } from "@/lib/types";

export const outings: Outing[] = [
  {
    id: "outing-1",
    title: "Indie Film Night + Dessert",
    description:
      "Catch a buzzy indie premiere at Coolidge Corner, then share dessert with your group at a nearby café.",
    categoryId: "movies",
    cityId: "boston",
    venue: "Coolidge Corner Theatre",
    neighborhood: "Brookline",
    date: "2026-07-12",
    startTime: "19:00",
    endTime: "22:30",
    groupSizeMin: 3,
    groupSizeMax: 6,
    pricing: { oneOff: 38, categoryPass: 33, allAccess: 28, discounted: 22 },
    included: ["Movie ticket", "Dessert at partner café", "Group matching"],
    notIncluded: ["Drinks at café", "Transportation"],
    extras: [
      {
        type: "dessert",
        description: "Shared dessert platter at Paris Creperie",
        includedInPrice: true,
      },
    ],
    accessibilityNotes: "Wheelchair accessible theater. Elevator available.",
    cancellationRules:
      "Free cancellation up to 48 hours before. Late cancellations may incur a penalty.",
    ticketDeliveryNote: "Tickets delivered in-app 24 hours before the outing.",
    spotsRemaining: 8,
    status: "open",
    imageGradient: "from-violet-600/40 to-fuchsia-500/30",
  },
  {
    id: "outing-2",
    title: "Comedy Cellar Showcase",
    description:
      "An evening of rising stand-up stars followed by optional bar reservations for your group.",
    categoryId: "comedy",
    cityId: "boston",
    venue: "Laugh Boston",
    neighborhood: "Seaport",
    date: "2026-07-15",
    startTime: "20:00",
    endTime: "23:00",
    groupSizeMin: 3,
    groupSizeMax: 6,
    pricing: { oneOff: 42, categoryPass: 36, allAccess: 30, discounted: 24 },
    included: ["Comedy show ticket", "Reserved group seating", "Group matching"],
    notIncluded: ["Food & drinks", "Bar tab"],
    extras: [
      {
        type: "reservation",
        description: "Optional post-show bar reservation nearby",
        includedInPrice: false,
      },
    ],
    accessibilityNotes: "Venue has accessible seating. Contact support for needs.",
    cancellationRules: "Cancel 72+ hours ahead for full credit.",
    ticketDeliveryNote: "Digital tickets in-app.",
    spotsRemaining: 4,
    status: "open",
    imageGradient: "from-amber-500/40 to-orange-600/30",
  },
  {
    id: "outing-3",
    title: "Red Sox Night at Fenway",
    description:
      "Experience America's most beloved ballpark with a curated group of fellow fans.",
    categoryId: "sports",
    cityId: "boston",
    venue: "Fenway Park",
    neighborhood: "Fenway",
    date: "2026-07-18",
    startTime: "19:10",
    endTime: "22:30",
    groupSizeMin: 3,
    groupSizeMax: 6,
    pricing: { oneOff: 65, categoryPass: 58, allAccess: 50, discounted: 40 },
    included: ["Game ticket", "Group meetup spot", "Group matching"],
    notIncluded: ["Food & drinks at park", "Parking"],
    extras: [],
    accessibilityNotes: "Accessible seating available. ADA entrances on Yawkey Way.",
    cancellationRules: "Non-refundable within 7 days of game.",
    ticketDeliveryNote: "Mobile tickets transferred in-app.",
    spotsRemaining: 12,
    status: "open",
    imageGradient: "from-emerald-600/40 to-teal-500/30",
  },
  {
    id: "outing-4",
    title: "Huntington Theatre: New Play",
    description:
      "A thought-provoking new production at the Huntington, with pre-show mingling.",
    categoryId: "performing-arts",
    cityId: "boston",
    venue: "Huntington Theatre",
    neighborhood: "South End",
    date: "2026-07-20",
    startTime: "19:30",
    endTime: "22:00",
    groupSizeMin: 3,
    groupSizeMax: 6,
    pricing: { oneOff: 55, categoryPass: 48, allAccess: 42, discounted: 34 },
    included: ["Theater ticket", "Pre-show group meetup", "Group matching"],
    notIncluded: ["Intermission drinks", "Dinner"],
    extras: [],
    accessibilityNotes: "Assistive listening devices available.",
    cancellationRules: "Full credit if cancelled 5+ days ahead.",
    ticketDeliveryNote: "Tickets in-app.",
    spotsRemaining: 6,
    status: "open",
    imageGradient: "from-rose-500/40 to-pink-600/30",
  },
  {
    id: "outing-5",
    title: "Blockbuster + Late Bites",
    description:
      "Summer blockbuster at AMC with late-night bites at a Seaport restaurant.",
    categoryId: "movies",
    cityId: "boston",
    venue: "AMC Boston Common",
    neighborhood: "Downtown",
    date: "2026-07-22",
    startTime: "18:30",
    endTime: "22:00",
    groupSizeMin: 3,
    groupSizeMax: 6,
    pricing: { oneOff: 40, categoryPass: 35, allAccess: 30 },
    included: ["Movie ticket", "Restaurant reservation", "Group matching"],
    notIncluded: ["Meal cost", "Drinks"],
    extras: [
      {
        type: "restaurant",
        description: "Group reservation at Row 34",
        includedInPrice: false,
      },
    ],
    accessibilityNotes: "Theater and restaurant both wheelchair accessible.",
    cancellationRules: "48-hour cancellation window.",
    ticketDeliveryNote: "In-app delivery.",
    spotsRemaining: 10,
    status: "open",
    imageGradient: "from-blue-600/40 to-indigo-500/30",
  },
  {
    id: "outing-6",
    title: "Improv Night at Improv Asylum",
    description:
      "Fast-paced improv comedy with your new favorite people.",
    categoryId: "comedy",
    cityId: "boston",
    venue: "Improv Asylum",
    neighborhood: "North End",
    date: "2026-07-25",
    startTime: "21:00",
    endTime: "23:30",
    groupSizeMin: 3,
    groupSizeMax: 6,
    pricing: { oneOff: 35, categoryPass: 30, allAccess: 26 },
    included: ["Show ticket", "Group matching"],
    notIncluded: ["Drinks", "Late-night food"],
    extras: [],
    accessibilityNotes: "Ground floor venue.",
    cancellationRules: "72-hour policy.",
    ticketDeliveryNote: "Digital tickets.",
    spotsRemaining: 14,
    status: "open",
    imageGradient: "from-yellow-500/40 to-amber-600/30",
  },
  {
    id: "outing-7",
    title: "Boston Pops at Symphony Hall",
    description:
      "An orchestral evening at the iconic Symphony Hall with a curated group.",
    categoryId: "performing-arts",
    cityId: "boston",
    venue: "Symphony Hall",
    neighborhood: "Back Bay",
    date: "2026-07-28",
    startTime: "20:00",
    endTime: "22:30",
    groupSizeMin: 3,
    groupSizeMax: 6,
    pricing: { oneOff: 72, categoryPass: 64, allAccess: 55 },
    included: ["Orchestra ticket", "Pre-concert mingle", "Group matching"],
    notIncluded: ["Program booklet", "Intermission refreshments"],
    extras: [],
    accessibilityNotes: "Wheelchair seating available. Hearing loop installed.",
    cancellationRules: "7-day cancellation for credit.",
    ticketDeliveryNote: "In-app tickets.",
    spotsRemaining: 3,
    status: "waitlist",
    imageGradient: "from-purple-600/40 to-violet-500/30",
  },
  {
    id: "outing-8",
    title: "WooSox Minor League Night",
    description:
      "Affordable baseball fun at Polar Park with a social group.",
    categoryId: "sports",
    cityId: "boston",
    venue: "Polar Park",
    neighborhood: "Worcester",
    date: "2026-08-02",
    startTime: "18:35",
    endTime: "21:30",
    groupSizeMin: 3,
    groupSizeMax: 6,
    pricing: { oneOff: 28, categoryPass: 24, allAccess: 20 },
    included: ["Game ticket", "Group matching"],
    notIncluded: ["Food & merch"],
    extras: [],
    accessibilityNotes: "Fully accessible ballpark.",
    cancellationRules: "48-hour window.",
    ticketDeliveryNote: "Mobile tickets.",
    spotsRemaining: 18,
    status: "open",
    imageGradient: "from-green-600/40 to-lime-500/30",
  },
  {
    id: "outing-9",
    title: "Classic Film Revival",
    description: "A timeless classic on the big screen with post-film discussion.",
    categoryId: "movies",
    cityId: "boston",
    venue: "Brattle Theatre",
    neighborhood: "Harvard Square",
    date: "2026-06-28",
    startTime: "19:00",
    endTime: "21:30",
    groupSizeMin: 3,
    groupSizeMax: 6,
    pricing: { oneOff: 32, categoryPass: 28, allAccess: 24 },
    included: ["Movie ticket", "Group matching"],
    notIncluded: ["Snacks"],
    extras: [],
    accessibilityNotes: "Historic venue with limited ADA access — contact support.",
    cancellationRules: "Past outing.",
    ticketDeliveryNote: "Delivered.",
    spotsRemaining: 0,
    status: "ended",
    imageGradient: "from-slate-600/40 to-zinc-500/30",
  },
  {
    id: "outing-10",
    title: "Speakeasy Comedy Underground",
    description: "Intimate underground comedy in a hidden Back Bay venue.",
    categoryId: "comedy",
    cityId: "boston",
    venue: "The Bebop",
    neighborhood: "Back Bay",
    date: "2026-07-10",
    startTime: "20:30",
    endTime: "23:00",
    groupSizeMin: 3,
    groupSizeMax: 6,
    pricing: { oneOff: 38, categoryPass: 33, allAccess: 28 },
    included: ["Show ticket", "Group matching"],
    notIncluded: ["Drinks"],
    extras: [],
    accessibilityNotes: "Stairs to venue — no elevator.",
    cancellationRules: "Standard policy.",
    ticketDeliveryNote: "In-app.",
    spotsRemaining: 2,
    status: "open",
    imageGradient: "from-red-500/40 to-rose-600/30",
  },
];

export function getOutingById(id: string): Outing | undefined {
  return outings.find((o) => o.id === id);
}

export function getOutingsByCity(cityId: string): Outing[] {
  return outings.filter((o) => o.cityId === cityId && o.status !== "ended");
}

export function getOutingsByCategory(categoryId: string): Outing[] {
  return outings.filter((o) => o.categoryId === categoryId && o.status !== "ended");
}

export function getRecommendedOutings(cityId: string, limit = 4): Outing[] {
  return outings
    .filter((o) => o.cityId === cityId && o.status === "open")
    .slice(0, limit);
}
